iGymConnect/iGymConnect/Controllers/CheckInController.cs
using BusinessLogic.ObjectModel;
using BusinessLogic.UserMag;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iGymConnect.Controllers
{
    public class CheckInController : Controller
    {
        // GET: CheckIn
        public ActionResult CheckIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveCheckIn(int MemberId)
        {
            var mem = BMember.GetAllByMember().FirstOrDefault(x => x.MemberId == MemberId);
            if (mem != null && mem.MemberId == MemberId)
            {
                var memship = BMembership.GetAllByMembership().FirstOrDefault(x => x.MembershipTypeId == mem.Membershiptypeid);
                if (memship.InActiveDate < DateTime.Now)
                {
                    return Json(new { isSuccess = false, responseMsg = "Your membership is expired, Please contact support administrator." });
                }
                else
                {
                    var checkin = BMCheckIn.SaveCheckIn(MemberId);
                    return Json(new { isSuccess = true, responseMsg = new { checkinDetails = checkin, memberDetails = mem, membershipdetail = memship } });
                }
            }
            else
            {
                return Json(new { isSuccess = false, responseMsg = "Member not found." });
            }

        }
    }
}

iGymConnect/iGymConnect/Controllers/DashboardController.cs
using BusinessLogic.ObjectModel;
using BusinessLogic.UserMag;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iGymConnect.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(OMUser model)
        {
            if (BUser.GetByUserNameAndPassword(model).Count > 0)
            {
                return RedirectToAction("MembershipView", "MamberShip");
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        //****************UserDetails**************//

        public ActionResult GetUserDetail(OMUser usr)
        {
            var user = BUser.GetByUserNameAndPassword(usr);
            return View("_UpdateProfile", user);
        }
        [HttpPost]
        public ActionResult UpdateUser(OMUser usr)
        {
            var user = BUser.UpdateUserDetails(usr);
            return Json(user);
        }

        //***********Change Password***********//
        public ActionResult Changepwd(OMUser user)
        {
            var u = BUser.GetByUserNameAndPassword(user);
            return View("_Changepassword", u);
        }
        [HttpPost]
        public ActionResult ChangePassword(int Id, string Username, string Password, string NewPassword)
        {
            //var u = BUser.GetAllUser().FirstOrDefault(x => x.Username == Username);

            var pwdchng = BUser.GetPasswordChanged(Id, Username, NewPassword);

            return Json(pwdchng);
        }
       

    }

}

iGymConnect/iGymConnect/Controllers/POSController.cs
using BusinessLogic.ObjectModel;
using BusinessLogic.UserMag;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iGymConnect.Controllers
{
    public class POSController : Controller
    {
        // GET: POS
        public ActionResult GetInventory()
        {
            var p = BMember.GetAllByMember().ToList();
            ViewBag.AllMember = p;
            var q = BCardMaster.GetAllCard().ToList();
            ViewBag.AllCard = q;

            return View(BCategory.GetAllCategories());
        }


        //Select Member Master Details
        public ActionResult SelectMember(int Id)
        {
            var m = BTransaction.GetAllTransaction().FirstOrDefault(x => x.MemberId == Id);
            return Json(m);
        }
        public ActionResult GetInvntoryByCategoryId(int Id)
        {
            var inv = BInventory.GetAllInventory().Where(x => x.CategoryId == Id)
                .Select(x => new OMInventory
                {
                    Id = x.Id,
                    Item = x.Item,
                    VendorId = x.VendorId,
                    CategoryId = x.CategoryId,
                    Description = x.Description,
                    Discount = x.Discount,
                    Cost = x.Cost,
                    Barcode = x.Barcode
                }).ToList();

            return Json(inv, JsonRequestBehavior.AllowGet);

        }
        //Add Quantity in Inventory********
        public ActionResult AddQty(int Id)
        {
            var invData = BInventory.GetAllInventory().FirstOrDefault(x => x.Id == Id);

            return Json(invData, JsonRequestBehavior.AllowGet);
        }
        //Check Duplication Vendor**************
        public bool CheckDulplicationVendor(int Id, string Name)
        {
            var ven = BVendor.GetAllVendors();
            if (Id > 0)
            {
                ven = ven.Where(x => x.Id != Id && x.Name == Name).ToList();
            }
            else
            {
                ven = ven.Where(x => x.Name == Name).ToList();
            }
            if (ven.Count > 0)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        //Check Duplication Category**************
        public bool CheckDulplicationCategory(int Id, string CategoryName)
        {
            var cat = BCategory.GetAllCategories();
            if (Id > 0)
            {
                cat = cat.Where(x => x.Id != Id && x.CategoryName == CategoryName).ToList();
            }
            else
            {
                cat = cat.Where(x => x.CategoryName == CategoryName).ToList();
            }
            if (cat.Count > 0)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        //Check Duplication Inventory***********
        public bool CheckDulplicationInventory(int Id, string InventoryName)
        {
            var inv = BInventory.GetAllInventory();
            if (Id > 0)
            {
                inv = inv.Where(x => x.Id != Id && x.Item == InventoryName).ToList();
            }
            else
            {
                inv = inv.Where(x => x.Item == InventoryName).ToList();
            }
            if (inv.Count > 0)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        //Check Duplication Inventory***********
        public bool CheckDulplicationCard(int Id, int Number)
        {
            var card = BCardMaster.GetAllCard();
            if (Id > 0)
            {
                card = card.Where(x => x.Id != Id && x.Number == Number).ToList();
            }
            else
            {
                card = card.Where(x => x.Number == Number).ToList();
            }
            if (card.Count > 0)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        //Cash Payment***********
        public ActionResult CashPayment(int Id)
        {
            var inv = BInventory.GetAllInventory().FirstOrDefault(x => x.Id == Id);
            return Json(inv, JsonRequestBehavior.AllowGet);
        }


        //Transaction Master *****[ CASH ]************
        [HttpPost]
        public ActionResult GetAllByTransactionMaster(OMTransaction tran)
        {
            var transaction = BTransaction.Save(tran);
            return Json(transaction);

        }
        //Card Master *****[ GIFT CARD ]************
        //public ActionResult GetCardItems(OMCardMaster card)
        //{
        //    var CardItems = BCardMaster.SaveCardItems(card);
        //    return Json(CardItems, JsonRequestBehavior.AllowGet);
        //}

        //********* Barcode Scanner ***********
        public ActionResult GetAllByBarcode(string Barcode)
        {
            var b = BInventory.GetAllInventory().FirstOrDefault(x => x.Barcode == Barcode);
            return Json(b, JsonRequestBehavior.AllowGet);
        }

        //********* Barcode Scanner ***********
        public ActionResult GetAllByCard()
        {
            var z = BMember.GetAllByMember().ToList();
            ViewBag.MemberList = z;
            var y = BCardMaster.GetCard().ToList();
            ViewBag.CardList = y;
            return View("_GiftCard");
        }
        //********* New Card Generate ***********
        public ActionResult GenerateCard(int From, int To, decimal Amount, DateTime ExpiryDate)
        {
            if (BCardMaster.Save(From, To, Amount, ExpiryDate) == 0)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }
        [HttpPost]
        public ActionResult GetMemberIdInCard(int MemberId, int Number)
        {
            var mem = BCardMaster.GetMemberAndCard(MemberId, Number);
            return Json(mem);
        }

        //******* Get Card numbers by Member *********
        public ActionResult GetCardNoByMember(int Id)
        {
            var card = BPOSCardMaster.GetCardByMember(Id);
            var usedCards = BTransaction.GetCardItems(0);
            if (usedCards != null)
            {
                foreach (var usedCard in usedCards)
                {
                    var foundCard = card.FirstOrDefault(x => x.Id == usedCard.CardId);
                    if (foundCard != null)
                    {
                        card.Remove(foundCard);
                    }
                }
            }
            return Json(card, JsonRequestBehavior.AllowGet);

        }
        //******* Get Card Details *********
        public ActionResult GetCardDetails(int Id)
        {
            var card = BCardMaster.GetAllCard().FirstOrDefault(x => x.Id == Id);
            return Json(card, JsonRequestBehavior.AllowGet);

        }

        //********* Category ***********
        public ActionResult SaveCategory(OMCategory cat)
        {
            var category = BCategory.Save(cat);
            return Json(category);
        }
        [HttpPost]
        public ActionResult SaveCategory(OMCategory cat, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var fileName = file.FileName;
                var path = Server.MapPath("~/Content/CategoryImages/") + fileName;
                file.SaveAs(path);
                cat.Image = file.FileName;
            }
            var category = BCategory.Save(cat);
            return Json(category);
        }
        public ActionResult GetCategories()
        {
            var categories = BCategory.GetAllCategories();
            ViewBag.AllCategory = categories;
            var abc = BCategory.GetAllCategories().ToList();
            ViewBag.ParentCategoryList = abc;
            return View("_Category", categories);
        }
        [HttpPost]
        public ActionResult DeleteCategory(int Id)
        {
            var inv = BInventory.GetAllInventory().FirstOrDefault(x => x.CategoryId == Id);

            if (inv != null)
            {
                return Json(new { responseMsg = "Category Is In Used,You Can't Delete Category" });
            }
            else
            {
                var i = BCategory.Delete(Id);
                return Json(new { responseMsg = "Category Deleted Successfully." });
            }
        }

        public ActionResult ShowCategoryDetails(int Id)
        {
            var cat = BCategory.GetAllCategories().FirstOrDefault(x => x.Id == Id);

            return Json(cat, JsonRequestBehavior.AllowGet);
        }

        //******* Vendor *********
        public ActionResult GetVendors()
        {
            var vendors = BVendor.GetAllVendors();
            return View("_Vendor", vendors);
        }

        public ActionResult SaveVendor(OMVendor vendor)
        {
            var ven = BVendor.Save(vendor);
            return Json(ven);
        }

        public ActionResult DeleteVendor(int Id)
        {
            var ven = BVendor.Delete(Id);
            return Json(ven);
        }
        public ActionResult ShowVendorDetails(int Id)
        {
            var ven = BVendor.GetAllVendors().FirstOrDefault(x => x.Id == Id);
            return Json(ven, JsonRequestBehavior.AllowGet);
        }


        //********* Inventory ***********
        public ActionResult GetInventories()
        {
            var Inventories = BInventory.GetAllInventory();

iGymConnect/iGymConnect/Views/Shared/_Category.cshtml
@model List<BusinessLogic.ObjectModel.OMCategory>
<div class="modal fade" id="myCategory" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"> CATEGORIES </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4" >
                        <div style="overflow-y:scroll;">
                        <table id="tblCategories" class="table table-bordered table-hover table-striped">
                            <thead>
                                <tr>
                                    <td>
                                        Name
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var cat in Model)
                                    {
                                        <tr data-categoryId="@cat.Id">
                                            <td>
                                                @cat.CategoryName
                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                            </div>
                    </div>
                    <div class="col-md-4">
                        <form class="form-horizontal" id="frmCategory">

                            <input type="hidden" class="form-control" id="txtCategoryId" >
                            <input type="hidden" class="form-control" id="txtpath">
                            <div class="form-group">
                                <label for="exampleInputName2">Category Name<span style="display:inline; color:red">  *</span></label>
                                <input type="text" class="form-control" id="txtCategoryName" placeholder="Enter Category">
                                <span style="display:none" id="lblName">Please enter Name</span>
                                <span style="display:none; color:red" id="lblVal">Name Is Mandatory</span>
                                <span style="display:none; color:red" id="lblValCat"> Already Exists </span>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail2">Description</label>
                                <textarea class="form-control" id="txtDesc" placeholder="Describe"></textarea>
                                
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail2">Browse From</label>
                                <input type="file" class="form-control" id="fuBrowseFrom"> 
                                
                                
                            </div>
                            <div class="form-group">
                                <label for="exampleInputName2">Parent Category List</label>
                                @Html.DropDownList("ddlCategory", new SelectList(ViewBag.ParentCategoryList, "Id", "CategoryName"), "-- Select --", new { @class = "form-control" })
                            </div>
                        </form>
                     </div>
                    <div class="col-lg-4">
                            <div align="center">
                                <img id="img" style="width:200px; height:200px;" /><br />
                                <br />
                                <input type="reset" id="ImgReset" value="Clear" class="btn btn-primary" />
                            </div>
                        
                    </div>
                </div>
            </div>
            <div>
                <div class="modal-footer">
                    <button type="button" id="btnCatReset" class="btn btn-primary">Add New</button>
                    <button type="button" id="btnCatSave" class="btn btn-primary">Save</button>
                    <button type="button" id="btnCatDel" class="btn btn-primary">Delete</button>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    

    function CatValidation() {
        var isSuccess = true;
        if ($('#txtCategoryName').val().length == 0) {
            $('#lblName').show();
            isSuccess = false;
        }
        else {
            $('#lblName').hide();
        }
        return isSuccess;
    }
    $(document).ready(function () {
        $('#fuBrowseFrom').change(function () {
            var url = $(this).val();
            var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
            if (this.files && this.files[0] && (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg")) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#img').attr('src', e.target.result);
                    $('#txtpath').attr('src', e.target.result);
                }
                reader.readAsDataURL(this.files[0]);
            }
            else {
                $('#img').attr('src', '~/Content/CategoryImages/');
              //  $('#txtpath').attr('src', '/Content/CategoryImages/');
            }
        });

        $('#btnCatSave').on('click', function () {
            var $file = document.getElementById('fuBrowseFrom'),
            $formData = new FormData();
            $formData.append('Id', $('#txtCategoryId').val());
            $formData.append('CategoryName', $('#txtCategoryName').val());
            $formData.append('Description', $('#txtDesc').val());
            $formData.append('ParentId', $('#ddlCategory').val());
            if($file.files.length > 0) {
                $formData.append('file', $file.files[0]);
            }
            if (CatValidation()) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("SaveCategory","POS")',
                    data: $formData, //{ CategoryId: $('#txtCategoryId').val(), CategoryName: $('#txtCategoryName').val(), Description: $('#txtDesc').val(),},
                    dataType: 'json',
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $.each(data, function (index, element) {
                            //alert(element.CategoryName);
                           
                        });
                        location.reload();
                        //window.location.href = window.location.href
                    }
                });

            }
        });
        $('#tblCategories tbody tr').on('click', function () {
            $.ajax({
                type: "GET",
                url: '@Url.Action("ShowCategoryDetails","POS")',
                data: { Id: $(this).data('categoryid') },
                success: function (data) {
                    if (data != null) {
                        $('#txtCategoryId').val(data.Id);
                        $('#txtCategoryName').val(data.CategoryName);
                        $('#txtDesc').val(data.Description);
                        // $('#fuBrowseFrom').val(data.Image);
                        var src1 = '@Url.Content("~/Content/CategoryImages/")' + data.Image;
                       //  var src1 = '/Content/CategoryImages' + data.Image;
                        $('#img').attr('src',src1);
                        $('#ddlCategory').val(data.ParentId);
                    }
                }
            });

            //alert($(this).data('CategoryId'));
        });

        $('#btnCatReset').on('click', function () {
            $('#img').attr('src', '');
            document.getElementById("frmCategory").reset();
        });

        $('#ImgReset').on('click', function () {
            $('#img').attr('src', '');
           
          });

        $('#btnCatDel').on('click', function () {
            $.ajax({
                type: "POST",
                url: '@Url.Action("DeleteCategory", "POS")',
                data: { Id: $('#txtCategoryId').val() },
                success: function (data) {
                    if (data.responseMsg)
                    {
                        alert(data.responseMsg);
                    }
                   // if (data != null) {
                   //     alert("Category Is In Used,You Can't Delete Category");
                   // }
                   // else {
                   //     //var a = confirm("Are You Sure?");
                   //     alert("Category Deleted Succesfully");
                   //}
                    location.reload();
                    //window.location.href = window.location.href
                }
            });
        });

        $('#txtCategoryName').keypress(function (e) {
            var regex = new RegExp("^[a-zA-Z ]");
            var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
            if (regex.test(str)) {
                $('#lblVal').hide();
                   return true;
            }
            $('#lblVal').show();
            e.preventDefault();
            return false;
            
        });
        $('#txtCategoryName').keyup(function () { 
            $.ajax({
                type: "POST",
                url: '@Url.Action("CheckDulplicationCategory", "POS")',
                data: { Id: $('#txtCategoryId').val() == "" ? "0" : $('#txtCategoryId').val(), CategoryName: $('#txtCategoryName').val() },
                success: function (data) {
                    if (data == 'True') {
                        alert("Category exists");
                        $('#lblValCat').show();
                    }
                    else {
                        $('#lblValCat').hide();
                    }
                }

            });
        });
      });
</script>

iGymConnect/iGymConnect/Views/Shared/_Changepassword.cshtml
@model List<BusinessLogic.ObjectModel.OMUser>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var user = (BusinessLogic.ObjectModel.OMUser)Session["UserLogin"];
}


<div id="Changepwd" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h1 class="modal-title" id="myModalLabel">Change Password</h1>
            </div>
            <div class="modal-body">
                <form id="chngpwd" class="form-horizontal">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-4 control-label">User Name:</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="txtUnm" value="@(""+ user.Username)">
                            <span style="display:none" id="lblun">Please enter Name</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-4 control-label">Old Password</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" id="txtOldPwd" placeholder="Enter Old Password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-4 control-label">New Password</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" id="txtNewPwd" placeholder="Enter New Password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-4 control-label">Confirm Password</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" id="txtCPwd" placeholder="Confirm Password">
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <span style="display:none; color:red" id="lblValChngPwd">New Password And Confirm Password Do Not Match</span>    
                    </div>
                    
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="btnuAdd">Edit</button>
                <button type="button" class="btn btn-default " data-dismiss="modal" id="btnClr">Cancel</button>
            </div>
        </div>
    </div>
</div> 




<script src="@Url.Content("~/scripts/jquery-1.10.2.min.js")"></script>

<script src="@Url.Content("~/scripts/bootstrap.min.js")"></script>
<script>
    function ChngPwdValidation() {
        var isSuccess = true;
        if ($('#txtUnm').val().length == 0) {
            $('#lblChngPwdName').show();
            isSuccess = false;
        }
        else {
            $('#lblChngPwdName').hide();
        }
        return isSuccess;
    }   
       $(document).ready(function () {

        $('#btnChngPwd').on('click', function () {
            if (ChngPwdValidation()) {
            $.ajax({
                    type: "POST",
                    url: '@Url.Action("ChangePassword", "Dashboard")',
                    data: { Id: $('#txtChngPwdId').val(), UserName: $('#txtUnm').val(), Password: $('#txtOldPwd').val(), NewPassword: $('#txtNewPwd').val() },
                    success: function (data) {
                        if (data != null)
                        {                           
                            alert("Password Changed Successfully");
                        }                        
                        window.location.reload();
                    }
                });
            }
        });
        
           $('#txtCPwd').keyup(function (e) {
               var password = $("#txtNewPwd").val();
               var confirmPassword = $("#txtCPwd").val();
               if (password != confirmPassword) {
                   $('#lblValChngPwd').show();
                   return false;
               }
               else {
                   $('#lblValChngPwd').hide();
                   return true;
               }
           });
    });
</script>